#!/usr/bin/env python3
"""
build_news_archive.py

Reads data/news_recent.json (structure:
{
  "generated_at": "...",
  "days_back": 30,
  "total_items": ...,
  "items": [ ... ]
}
)
and updates monthly and yearly archive files in:

- data/archive/monthly/<year>/<year>-<month>.json
- data/archive/yearly/<year>.json

Each file is a LIST of items (same item structure as news_recent.json).
The script is idempotent: it can run multiple times because it merges and deduplicates.

It also processes `promo_filtered_*.json` debug files generated by
build_news_json.py, aggregating them into monthly promo files:

- data/archive/promo/monthly/<year>/promo_<year>-<month>.json

After processing, `data/archive/promo_filtered_*.json` files are deleted.
"""

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from json import JSONDecodeError


# Base paths
BASE_DIR = Path(__file__).resolve().parents[1]
DATA_DIR = BASE_DIR / "data"
RECENT_PATH = DATA_DIR / "news_recent.json"

ARCHIVE_DIR = DATA_DIR / "archive"
MONTHLY_DIR = ARCHIVE_DIR / "monthly"
YEARLY_DIR = ARCHIVE_DIR / "yearly"
ARCHIVE_INDEX_PATH = ARCHIVE_DIR / "archive_index.json"
ARCHIVE_GLOBAL_INDEX_PATH = ARCHIVE_DIR / "index.json"

PROMO_DIR = ARCHIVE_DIR / "promo"
PROMO_MONTHLY_DIR = PROMO_DIR / "monthly"

MORNING_CALL_DIR = ARCHIVE_DIR / "morning_call"


# ---------- I/O utilities ----------



def load_json_any(path: Path) -> Any:
    if not path.exists():
        return None

    try:
        raw = path.read_text(encoding="utf-8")
    except OSError as e:
        print(f"[WARN] Failed to read {path}: {e}")
        return None

    # File exists but is empty / whitespace
    if not raw.strip():
        print(f"[WARN] Empty JSON at {path}. Treating as 'None'.")
        return None

    try:
        return json.loads(raw)
    except JSONDecodeError as e:
        # Rename the corrupt file so future runs do not break.
        ts = datetime.now(timezone.utc).strftime("%Y%m%d_%H%M%S")
        corrupt = path.with_suffix(path.suffix + f".corrupt_{ts}")
        try:
            path.rename(corrupt)
            print(f"[WARN] Invalid JSON at {path}. Renamed to {corrupt}. Error: {e}")
        except OSError:
            print(f"[WARN] Invalid JSON at {path} (could not rename). Error: {e}")
        return None

def load_json_list(path: Path, root_key: Optional[str] = None) -> List[Dict[str, Any]]:
    """
    Loads JSON and guarantees a list of dicts.
    - If root_key is provided (for example 'items'), reads from an object {root_key: [...]}
    - If the file is already a list, returns it directly
    - If it is empty/corrupt, returns []
    """
    data = load_json_any(path)
    if data is None:
        return []

    if root_key:
        if isinstance(data, dict):
            val = data.get(root_key, [])
            return val if isinstance(val, list) else []
        return []

    # No root_key: accept a list directly.
    if isinstance(data, list):
        return data

    # If someone saves a dict by mistake, try a common fallback.
    if isinstance(data, dict):
        val = data.get("items")
        if isinstance(val, list):
            return val

    print(f"[WARN] JSON at {path} is not a list (and does not contain '{root_key or 'items'}'). Ignoring.")
    return []


def save_json_list(path: Path, items: List[Dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)

    # Atomic write: write to tmp, then replace.
    tmp = path.with_suffix(path.suffix + ".tmp")
    with tmp.open("w", encoding="utf-8") as f:
        json.dump(items, f, ensure_ascii=False, indent=2)

    tmp.replace(path)



# ---------- Date helpers ----------

def parse_datetime(value: Any) -> Optional[datetime]:
    """
    Attempts to convert a date field (ISO string or numeric timestamp) into datetime.
    """
    if value is None:
        return None

    if isinstance(value, (int, float)):
        # Assume timestamp in seconds.
        return datetime.fromtimestamp(float(value), tz=timezone.utc)

    if isinstance(value, str):
        # tenta ISO 8601
        try:
            # datetime.fromisoformat may not understand 'Z', so normalize it.
            if value.endswith("Z"):
                value = value[:-1] + "+00:00"
            return datetime.fromisoformat(value)
        except Exception:
            return None

    return None


def ensure_timestamp(item: Dict[str, Any]) -> float:
    """
    Ensures each item has a numeric 'published_ts' field (epoch seconds)
    derived from 'published' (ISO string) or an existing 'published_ts'.
    """
    ts = item.get("published_ts")
    if isinstance(ts, (int, float)):
        return float(ts)

    dt = parse_datetime(item.get("published")) or parse_datetime(item.get("updated"))
    if dt is None:
        # Fallback: now.
        dt = datetime.now(timezone.utc)

    item["published_ts"] = dt.timestamp()
    return item["published_ts"]


def _summarize_items(items: List[Dict[str, Any]]) -> Dict[str, Any]:
    total = len(items)
    if total == 0:
        return {
            "item_count": 0,
            "range_start": None,
            "range_end": None,
        }

    min_ts = None
    max_ts = None
    for it in items:
        ts = ensure_timestamp(it)
        if min_ts is None or ts < min_ts:
            min_ts = ts
        if max_ts is None or ts > max_ts:
            max_ts = ts

    range_start = datetime.fromtimestamp(min_ts, tz=timezone.utc).isoformat() if min_ts is not None else None
    range_end = datetime.fromtimestamp(max_ts, tz=timezone.utc).isoformat() if max_ts is not None else None
    return {
        "item_count": total,
        "range_start": range_start,
        "range_end": range_end,
    }


# ---------- Month/year bucketing ----------

def bucket_items_by_month(items: List[Dict[str, Any]]) -> Dict[Tuple[int, int], List[Dict[str, Any]]]:
    """
    Groups items by (year, month) based on published_ts / published.
    """
    buckets: Dict[Tuple[int, int], List[Dict[str, Any]]] = {}

    for it in items:
        ts = ensure_timestamp(it)
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
        key = (dt.year, dt.month)
        buckets.setdefault(key, []).append(it)

    return buckets


def bucket_items_by_year(items: List[Dict[str, Any]]) -> Dict[int, List[Dict[str, Any]]]:
    """
    Groups items by year.
    """
    buckets: Dict[int, List[Dict[str, Any]]] = {}

    for it in items:
        ts = ensure_timestamp(it)
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
        key = dt.year
        buckets.setdefault(key, []).append(it)

    return buckets


# ---------- Merge + dedup por link ----------

def merge_and_dedup(existing: List[Dict[str, Any]], new: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """
    Merges existing + new lists, deduplicating primarily by `link`.
    If there is no link, uses (title, source) as a fallback.
    """
    merged: Dict[Any, Dict[str, Any]] = {}

    def key_for(item: Dict[str, Any]) -> Any:
        link = item.get("link")
        if link:
            return ("link", link)
        return ("title_source", item.get("title"), item.get("source"))

    for item in existing + new:
        k = key_for(item)
        merged[k] = item

    # Convert back to a list and sort by published_ts desc.
    result = list(merged.values())

    def sort_key(it: Dict[str, Any]) -> float:
        dt = parse_datetime(it.get("published")) or parse_datetime(it.get("updated"))
        if dt is not None:
            return dt.timestamp()
        ts = it.get("published_ts")
        if isinstance(ts, (int, float)):
            return float(ts)
        return 0.0

    result.sort(key=sort_key, reverse=True)
    return result


# ---------- promo_filtered_* processing (feeds with promotional content) ----------

def _normalize_promo_item(item: Dict[str, Any], seen_at: datetime) -> Dict[str, Any]:
    """
    Normalizes a promo item to the format used by monthly files.

    Output fields:
      - feed_title
      - xml_url
      - type_label
      - first_seen / last_seen (ISO8601)
      - total_hits
      - examples (list of strings, maximum 10)
    """
    def _to_int(val: Any) -> int:
        try:
            return int(val)
        except (TypeError, ValueError):
            return 0

    promo_count = _to_int(item.get("promo_count", item.get("count", 0)))

    examples = item.get("examples") or []
    if not isinstance(examples, list):
        examples = [examples]
    examples = [str(e) for e in examples][:10]

    return {
        "feed_title": item.get("feed_title"),
        "xml_url": item.get("xml_url"),
        "type_label": item.get("type_label"),
        "first_seen": seen_at.isoformat(),
        "last_seen": seen_at.isoformat(),
        "total_hits": promo_count,
        "examples": examples,
    }


def _merge_promo_month_entries(
    existing: List[Dict[str, Any]],
    new_entries: List[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """
    Merges promo entries for the same month, aggregating by feed (xml_url or feed_title key).
    Sums total_hits, merges examples, and adjusts first_seen/last_seen.
    """
    merged: Dict[str, Dict[str, Any]] = {}

    def key_for(it: Dict[str, Any]) -> Optional[str]:
        return it.get("xml_url") or it.get("feed_title")

    def to_int(val: Any) -> int:
        try:
            return int(val)
        except (TypeError, ValueError):
            return 0

    def merge_one(target: Dict[str, Any], src: Dict[str, Any]) -> None:
        # Sum total_hits.
        target["total_hits"] = to_int(target.get("total_hits")) + to_int(
            src.get("total_hits", src.get("promo_count", 0))
        )

        # Merge examples (limited to 10).
        existing_examples = [str(e) for e in (target.get("examples") or [])]
        seen = set(existing_examples)
        src_examples = src.get("examples") or []
        for ex in src_examples:
            ex_str = str(ex)
            if ex_str not in seen:
                existing_examples.append(ex_str)
                seen.add(ex_str)
            if len(existing_examples) >= 10:
                break
        target["examples"] = existing_examples

        # Adjust first_seen / last_seen if present and ISO-formatted.
        src_first = src.get("first_seen")
        src_last = src.get("last_seen")

        if src_first:
            if not target.get("first_seen") or str(src_first) < str(target["first_seen"]):
                target["first_seen"] = src_first
        if src_last:
            if not target.get("last_seen") or str(src_last) > str(target["last_seen"]):
                target["last_seen"] = src_last

        # Keep the latest non-empty feed_title/xml_url/type_label values.
        for field in ("feed_title", "xml_url", "type_label"):
            if src.get(field):
                target[field] = src[field]

    # First, copy existing entries.
    for it in existing:
        k = key_for(it)
        if not k:
            continue
        merged[k] = dict(it)

    # Then aggregate new entries.
    for it in new_entries:
        k = key_for(it)
        if not k:
            continue
        if k in merged:
            merge_one(merged[k], it)
        else:
            # Ensure default fields.
            base = dict(it)
            base.setdefault("total_hits", to_int(it.get("total_hits", it.get("promo_count", 0))))
            base.setdefault("examples", it.get("examples") or [])
            merged[k] = base

    return list(merged.values())


def process_promo_filtered_files() -> None:
    """
    Finds data/archive/promo_filtered_*.json files, buckets them by month
    (based on file mtime), and writes/updates:

        data/archive/promo/monthly/<year>/promo_<year>-<month>.json

    After successful processing, promo_filtered_* files are deleted.
    """
    promo_files = sorted(ARCHIVE_DIR.glob("promo_filtered_*.json"))

    if not promo_files:
        print("[INFO] No promo_filtered_* files to process.")
        return

    monthly_new: Dict[Tuple[int, int], List[Dict[str, Any]]] = {}

    for path in promo_files:
        try:
            raw = load_json_any(path)
        except Exception as e:
            print(f"[WARN] Failed to read {path}: {e}")
            continue

        if raw is None:
            continue

        # Determine items inside the file.
        if isinstance(raw, list):
            items = raw
        elif isinstance(raw, dict):
            # Try a few common keys.
            if isinstance(raw.get("items"), list):
                items = raw["items"]
            elif isinstance(raw.get("feeds"), list):
                items = raw["feeds"]
            else:
                # Last resort: try to interpret dict values as a list of items.
                values = list(raw.values())
                if values and isinstance(values[0], list):
                    items = values[0]
                else:
                    print(f"[WARN] Unexpected format in {path}, ignoring.")
                    continue
        else:
            print(f"[WARN] Unexpected format in {path}, ignoring.")
            continue

        # Use file mtime to determine year/month.
        mtime = datetime.fromtimestamp(path.stat().st_mtime, tz=timezone.utc)
        year, month = mtime.year, mtime.month

        bucket_key = (year, month)
        bucket = monthly_new.setdefault(bucket_key, [])

        for it in items:
            if not isinstance(it, dict):
                continue
            norm = _normalize_promo_item(it, mtime)
            bucket.append(norm)

    # Update monthly promo files.
    for (year, month), new_entries in sorted(monthly_new.items()):
        year_str = f"{year}"
        month_str = f"{month:02d}"

        month_dir = PROMO_MONTHLY_DIR / year_str
        month_dir.mkdir(parents=True, exist_ok=True)
        promo_month_path = month_dir / f"promo_{year_str}-{month_str}.json"

        existing = load_json_list(promo_month_path)
        merged = _merge_promo_month_entries(existing, new_entries)
        save_json_list(promo_month_path, merged)

        print(
            f"[INFO] Monthly promo file updated: {promo_month_path} "
            f"(+{len(new_entries)} records, total {len(merged)})"
        )

    # Clean up input files after processing.
    for path in promo_files:
        try:
            path.unlink()
            print(f"[INFO] File processed and removed: {path}")
        except OSError as e:
            print(f"[WARN] Could not delete {path}: {e}")


def process_morning_call_files() -> None:
    """
    Moves flat files:
      data/archive/morning_call_YYYY-MM-DD.json
    to:
      data/archive/morning_call/<year>/<month>/morning_call_YYYY-MM-DD.json
    """
    mc_files = sorted(ARCHIVE_DIR.glob("morning_call_*.json"))
    if not mc_files:
        print("[INFO] No flat morning_call_*.json files to organize.")
        return

    for src in mc_files:
        # Safety: ignore anything that is not a regular file.
        if not src.is_file():
            continue

        # Try to extract the date from the JSON itself (analysis_date / generated_at);
        # otherwise use mtime.
        dt = None
        try:
            raw = load_json_any(src)
            if isinstance(raw, dict):
                if raw.get("analysis_date"):
                    dt = parse_datetime(str(raw["analysis_date"]) + "T00:00:00Z")
                if dt is None and raw.get("generated_at"):
                    dt = parse_datetime(raw.get("generated_at"))
        except Exception:
            dt = None

        if dt is None:
            dt = datetime.fromtimestamp(src.stat().st_mtime, tz=timezone.utc)

        year_str = f"{dt.year}"
        month_str = f"{dt.month:02d}"

        dest_dir = MORNING_CALL_DIR / year_str / month_str
        dest_dir.mkdir(parents=True, exist_ok=True)

        dest = dest_dir / src.name
        if dest.exists():
            # Avoid unnecessary overwrite.
            print(f"[INFO] Destination already exists, removing duplicate: {src} -> {dest}")
            src.unlink()
            continue

        src.rename(dest)
        print(f"[INFO] Morning call moved: {src} -> {dest}")


def build_archive_indices() -> None:
    """
    Generates global indexes for fast frontend navigation:
      - data/archive/archive_index.json
      - data/archive/index.json (alias with the same content)
    """
    years_map: Dict[int, Dict[str, Any]] = {}

    # 1) Monthly summaries
    for monthly_file in sorted(MONTHLY_DIR.glob("*/*.json")):
        try:
            year_str = monthly_file.parent.name
            file_name = monthly_file.stem  # YYYY-MM
            if "-" not in file_name:
                continue
            _, month_str = file_name.split("-", 1)
            year = int(year_str)
            month = int(month_str)
        except (ValueError, TypeError):
            continue

        items = load_json_list(monthly_file)
        month_summary = _summarize_items(items)

        y = years_map.setdefault(
            year,
            {
                "year": year,
                "item_count": 0,
                "range_start": None,
                "range_end": None,
                "months": [],
                "yearly_path": f"archive/yearly/{year}.json",
            },
        )

        y["months"].append(
            {
                "month": f"{month:02d}",
                "item_count": month_summary["item_count"],
                "range_start": month_summary["range_start"],
                "range_end": month_summary["range_end"],
                "path": f"archive/monthly/{year}/{year}-{month:02d}.json",
            }
        )
        y["item_count"] += int(month_summary["item_count"])

        # Update yearly range from months.
        start = month_summary["range_start"]
        end = month_summary["range_end"]
        if start and (not y["range_start"] or start < y["range_start"]):
            y["range_start"] = start
        if end and (not y["range_end"] or end > y["range_end"]):
            y["range_end"] = end

    # 2) Adjust metadata based on yearly files, if available.
    for yearly_file in sorted(YEARLY_DIR.glob("*.json")):
        try:
            year = int(yearly_file.stem)
        except ValueError:
            continue

        items = load_json_list(yearly_file)
        summary = _summarize_items(items)
        y = years_map.setdefault(
            year,
            {
                "year": year,
                "item_count": 0,
                "range_start": None,
                "range_end": None,
                "months": [],
                "yearly_path": f"archive/yearly/{year}.json",
            },
        )

        if summary["item_count"] > y["item_count"]:
            y["item_count"] = int(summary["item_count"])
        if summary["range_start"] and (not y["range_start"] or summary["range_start"] < y["range_start"]):
            y["range_start"] = summary["range_start"]
        if summary["range_end"] and (not y["range_end"] or summary["range_end"] > y["range_end"]):
            y["range_end"] = summary["range_end"]

    # Sort years/months.
    years = []
    for year in sorted(years_map.keys()):
        row = years_map[year]
        row["months"] = sorted(row["months"], key=lambda m: m["month"])
        years.append(row)

    # Totals and latest month.
    total_months = sum(len(y["months"]) for y in years)
    total_items = sum(int(y["item_count"]) for y in years)

    latest = None
    for y in sorted(years, key=lambda r: r["year"], reverse=True):
        if not y["months"]:
            continue
        last_month = sorted(y["months"], key=lambda m: m["month"], reverse=True)[0]
        latest = {
            "year": y["year"],
            "month": last_month["month"],
            "item_count": int(last_month["item_count"]),
            "path": last_month["path"],
        }
        break

    payload = {
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "latest": latest,
        "totals": {
            "years": len(years),
            "months": total_months,
            "items": total_items,
        },
        "years": years,
    }

    ARCHIVE_DIR.mkdir(parents=True, exist_ok=True)
    ARCHIVE_INDEX_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    ARCHIVE_GLOBAL_INDEX_PATH.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[INFO] Archive index generated: {ARCHIVE_INDEX_PATH}")
    print(f"[INFO] Global index generated: {ARCHIVE_GLOBAL_INDEX_PATH}")


# ---------- Main function ----------

def main() -> None:
    if not RECENT_PATH.exists():
        raise FileNotFoundError(f"Recent file not found: {RECENT_PATH}")

    # news_recent.json is a dict with "items".
    recent_items = load_json_list(RECENT_PATH, root_key="items")
    print(f"[INFO] Loaded {len(recent_items)} recent items from {RECENT_PATH}")

    if not recent_items:
        print("[INFO] No recent items to archive. Updating indexes/helpers only.")
        process_morning_call_files()
        process_promo_filtered_files()
        build_archive_indices()
        return

    # Buckets by month and year.
    monthly_buckets = bucket_items_by_month(recent_items)
    yearly_buckets = bucket_items_by_year(recent_items)

    # --------- Update monthly files ---------
    for (year, month), items in sorted(monthly_buckets.items()):
        year_str = f"{year}"
        month_str = f"{month:02d}"

        month_dir = MONTHLY_DIR / year_str
        month_path = month_dir / f"{year_str}-{month_str}.json"

        existing = load_json_list(month_path)
        merged = merge_and_dedup(existing, items)
        save_json_list(month_path, merged)

        print(
            f"[INFO] Monthly file updated: {month_path} "
            f"(+{len(items)} items, total {len(merged)})"
        )

    # --------- Update yearly files ---------
    for year, items in sorted(yearly_buckets.items()):
        year_str = f"{year}"
        year_path = YEARLY_DIR / f"{year_str}.json"

        existing = load_json_list(year_path)
        merged = merge_and_dedup(existing, items)
        save_json_list(year_path, merged)

        print(
            f"[INFO] Yearly file updated: {year_path} "
            f"(+{len(items)} items, total {len(merged)})"
        )

    # --------- Process promo_filtered_* files ---------
    process_morning_call_files()
    process_promo_filtered_files()
    build_archive_indices()

    print("[INFO] build_news_archive.py completed successfully.")


if __name__ == "__main__":
    main()
